### ISSUE TITLE
没有排除指令外的消息

### ISSUE THREAD

**Issue by NtskwK** [TDK1969/nonebot_plugin_bilibilibot#1]
发送与插件无关的消息也会返回
> ×未知指令，请检查……

这样已经干扰到了群里正常的交流

**Comment by TDK1969** [comment]
其实我还没有测试过把机器人放进群里，可以反馈一下使用结果吗（除了无关消息会返回未知指令）？

**Comment by NtskwK** [comment]
目前的情况是，除了发送已有指令外，其他大部分消息都会回复这一条
包括且不仅限于 ```文本```、```图片```、```回复信息``` 等。
我最近比较忙，可能要到下周才有空做进一步的测试

**Comment by TDK1969** [comment]
我自己也测试一下，现在机器人放在群里并没有在群里通知的能力，现在正在开发群通知的功能
如果想取消未知指令，可以在插件的__init__.py中将最后一个函数注释掉，即如下的代码
```
unknownMessage = on_message(rule=to_me, priority=30)
@unknownMessage.handle()
async def unknownMessageHandler(matcher: Matcher, event: MessageEvent):
    userID = event.get_user_id()
    logger.debug(f"用户{userID}发送了一条未知信息")
    msg = "❌未知指令，请检查输入或通过/help指令获取帮助"
    await unknownMessage.finish(msg)

**Comment by TDK1969** [comment]
新版本已经发布，请更新到2.0.0
新版本解决了这个问题，并且可以真正运用到群组中
感谢你的issue
