### ISSUE TITLE
推送错误

### ISSUE THREAD

**Issue by Colleen114514** [TDK1969/nonebot_plugin_bilibilibot#11]
![image](https://user-images.githubusercontent.com/106069303/169787205-1c676107-6098-4280-b1a3-7c0e8327f022.png)
订阅出现[    ERROR] plugins | B站订阅推送发生错误 sub_id：194484313 <class 'AttributeError'>：'NoneType' object has no attribute 'uid'

**Comment by TDK1969** [comment]
感谢你的反馈，请补充如下信息：

1. 你使用nonebot的环境、bilibilibot的版本等
2. 出现问题的完整日志内容，麻烦已文字形式放在代码块中方便查看
3. 该问题是否能稳定复现？
