### ISSUE TITLE
【报错】未推送

### ISSUE THREAD

**Issue by Agnes4m** [TDK1969/nonebot_plugin_bilibilibot#17]
python3.9.13,nonebot=2.0.0b4
是这样的，今天注意看了下，下午2点半的时候碧蓝发了一个推送，然后没看到推送.
看了下gocq的log，
```
[2022-08-11 13:58:31] [WARNING]: 群消息发送失败: 账号可能被风控. 
[2022-08-11 13:58:37] [WARNING]: 群消息发送失败: 账号可能被风控. 
[2022-08-11 14:35:00] [WARNING]: 群消息发送失败: 账号可能被风控. 

```
另外一个用haruka插件的，在2：29准时发送了推送，那本插件是有五分钟延时而且风控吗？
此外其他功能没有任何问题，暂时还没有nb端的log，后面看看再补
![image](https://user-images.githubusercontent.com/70925546/184080670-0605c471-4e59-4ebd-a14f-09f7632eedcf.png)

**Comment by TDK1969** [comment]
gocq的日志说账号被风控那多半是机器人的号被拿下了，建议登陆机器人账号处理一下，这可能是腾讯随机抽风，可能与本插件无关
为了避免过于频繁地调用b站的API，机器人设定了每90s查询一次up和主播的更新状态，如果想要自行调整可以修改__init__.py文件最下面的如下代码中的minutes参数：
```
scheduler.add_job(CheckBiliStream, "interval", minutes=1, id="biliStream", misfire_grace_time=90)
scheduler.add_job(CheckUpUpdate, "interval", minutes=1, id="biliUp", misfire_grace_time=90)
scheduler.add_job(CheckTeleUpdate, "interval", minutes=5, id="biliTele", misfire_grace_time=90)
```
