### ISSUE TITLE
【报错】成功关注主播和up主，但无法推送，日志也没任何报错

### ISSUE THREAD

**Issue by mogudunji** [TDK1969/nonebot_plugin_bilibilibot#19]
【报错】成功关注主播和up主，但无法推送，日志也没任何报错

**Comment by TDK1969** [comment]
请查看file目录下的对应json文件是否关注成功

**Comment by mogudunji** [comment]
> 
有相应的json文件

**Comment by TDK1969** [comment]
是视频更新了或主播开播了之后没有推送信息嘛

**Comment by mogudunji** [comment]
> 是视频更新了或主播开播了之后没有推送信息嘛

没错，无推送也没有报错

**Comment by TDK1969** [comment]
请问你有自己修改代码嘛

**Comment by mogudunji** [comment]
> 请问你有自己修改代码嘛

并没有，原先以为是调用api时间太长了，换成了10s一次调用，但仍然无法检测推送
