### ISSUE TITLE
直接pip install的话，运行时help指令会提示报错

### ISSUE THREAD

**Issue by zxz0415** [TDK1969/nonebot_plugin_bilibilibot#2]

**Comment by zxz0415** [comment]
with open('./src/plugins/nonebot_plugin_bilibilibot/file/source/help.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './src/plugins/nonebot_plugin_bilibilibot/file/source/help.txt'

**Comment by TDK1969** [comment]
预计今天更新版本，会进行修复

**Comment by TDK1969** [comment]
新版本已经发布，请更新到2.0.0，可以解决该问题
感谢你的issue
