### ISSUE TITLE
不能使用昵称关注，只能使用uid关注

### ISSUE THREAD

**Issue by thankU-ubi** [TDK1969/nonebot_plugin_bilibilibot#20]
![image](https://user-images.githubusercontent.com/104612463/186727412-a52fa641-8fde-47d6-96fd-4dc7b444c55b.png)
![image](https://user-images.githubusercontent.com/104612463/186727924-2f393a67-f8e4-4462-8972-dc967b10d1cf.png)
![image](https://user-images.githubusercontent.com/104612463/186728037-fe647be1-6d4b-402a-9106-ad73b42ac5c3.png)

08-26 01:11:28 [INFO] nonebot_plugin_gocqhttp | [2821521344] 收到群 测试群(1006443456) 内 THANKU.UB(609638635) 的消息: /关注up 嘉然今天吃什么 (574077710)
08-26 01:11:28 [SUCCESS] nonebot | ONEBOT V11 2821521344 | [message.group.normal]: Message 574077710 from 609638635@[群:1006443456] "/关注up 嘉然今天吃什么"
08-26 01:11:28 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_bilibilibot, type=message, priority=1, temp=False>
08-26 01:11:29 [INFO] nonebot_plugin_gocqhttp | [2821521344] 发送群 测试群(1006443456) 的消息: [{"type":  ... (1429244824)
08-26 01:11:29 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_bilibilibot, type=message, priority=1, temp=False> running complete
08-26 01:11:29 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_petpet, type=message, priority=12, temp=False>
08-26 01:11:29 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_petpet, type=message, priority=12, temp=False> running complete

**Comment by TDK1969** [comment]
抱歉，只能使用uid关注up主
