### ISSUE TITLE
运行插件的时候报了dir错误，是否是因为CheckDir没有被引用？

### ISSUE THREAD

**Issue by KaiOverflow** [TDK1969/nonebot_plugin_bilibilibot#22]
![image](https://user-images.githubusercontent.com/110107674/190838090-a1e49ba3-04db-4890-bab1-22eb916e4d7e.png)

**Comment by TDK1969** [comment]
这是旧版本代码的问题。若在修复前想正常使用，请将db.py文件中的最后一行bili_database.get_from_json()注释掉，即可正常运行。
