### ISSUE TITLE
后台报错KeyError:'list'，同时群内多次重复推送

### ISSUE THREAD

**Issue by MYHZZD** [TDK1969/nonebot_plugin_bilibilibot#24]
![O14AYN%`A(J0U{HPA89RG(T](https://user-images.githubusercontent.com/90319337/191274317-2ea78c29-4fe3-41b4-9ae9-04bc0511ec1e.png)
![image](https://user-images.githubusercontent.com/90319337/191274656-3cb66f1a-6cbe-4bde-bf8d-bd5042d1c807.png)

检索每个关注的主播时都报错，同时在群内数十次发送重复的开播公告

**Comment by citydirector** [comment]
+1

**Comment by TDK1969** [comment]
这是由于查询B站接口频率过高，触发了反爬虫机制，现在正在研究IP代理池进行修复。
在修复完成前为了避免该问题，请修改`__init__.py`中最后三行的`scheduler.add_job`语句中的minutes参数，建议修改到3~5以降低查询频率。

**Comment by TDK1969** [comment]
已修复该问题，请更新到2.2.0
