### ISSUE TITLE
希望能关注 哔哩哔哩番剧出差

### ISSUE THREAD

**Issue by Afurete233** [TDK1969/nonebot_plugin_bilibilibot#28]

**Comment by TDK1969** [comment]
这个账号不能关注 我也不知道为什么 我搜索可以搜到 但是无法打开他的个人空间

**Comment by Afurete233** [comment]
因为这个账号被屏蔽了，可以看看几个插件的破解方法
[解除B站区域限制](https://github.com/ipcjs/bilibili-helper/tree/user.js/packages/unblock-area-limit)
[哔哩漫游](https://github.com/yujincheng08/BiliRoaming)

**Comment by TDK1969** [comment]
暂时不打算实现
