### ISSUE TITLE
关于报错no such column: FALSE

### ISSUE THREAD

**Issue by FairyReimu** [TDK1969/nonebot_plugin_bilibilibot#29]
> File "apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "nonebot_plugin_bilibilibot/biliTelegram.py", line 35, in check_telegram_update
    telegram_list = bili_database.query_all(2)
  File "nonebot_plugin_bilibilibot/db.py", line 254, in query_all
    raise BiliDatebaseError(f"数据库查询信息表时发生错误:{e.args[0]}")
onebot_plugin_bilibilibot.exception.BiliDatebaseError: 数据库查询信息表时发生错误:no such column: FALSE

在获得所有up以进行更新检测时便出现如上报错；
此时只关注了两三位up

看了感觉语句也没什么问题，而其他功能均正常，因此不知如何解决

**Comment by TDK1969** [comment]
请问是哪一个版本出现的问题？

**Comment by FairyReimu** [comment]
> 

当前版本，而且之前也存在
Python 3.8.2
SQLite version 3.7.17

**Comment by FairyReimu** [comment]
> 请问是哪一个版本出现的问题？

![image](https://user-images.githubusercontent.com/90098435/197739969-3f14cbbf-ee36-409e-b273-12715671bc58.png)
haoxs好像是这条语句的问题，加上单引号就正常了

**Comment by TDK1969** [comment]
我的sqlite版本为2.6.0，可能是版本之间不同发生的问题

**Comment by TDK1969** [comment]
请尝试将db.py中的那个语句修改为
`SELECT season_id, telegram_title, episode FROM telegram WHERE is_finish = 0`，能否正确处理？

**Comment by FairyReimu** [comment]
> 请尝试将db.py中的那个语句修改为 `SELECT season_id, telegram_title, episode FROM telegram WHERE is_finish = 0`，能否正确处理？

之前加了单引号就没问题了，估计是布尔值在不同版本的表现问题，这种改成0和1也肯定没问题

**Comment by TDK1969** [comment]
在版本2.2.2中已修复
