### ISSUE TITLE
未推送

### ISSUE THREAD

**Issue by 0ceanCat** [TDK1969/nonebot_plugin_bilibilibot#30]
![image](https://user-images.githubusercontent.com/58326657/197821342-d31a9c5d-3b83-439c-8a3f-6b5a91f8ef7f.png)
查询成分显示确实关注了我的B站，可是我发表了个测试动态5分钟内都没有任何反应。
环境：Python 3.8.10
           Ubuntu 20.04 LTS x64

为了测试只安装了此库和此库需要的插件。

**Comment by 0ceanCat** [comment]
10分钟了，应该是不会有反应了

**Comment by TDK1969** [comment]
暂未实现关注动态的功能，目前只支持发布视频、开启直播以及番剧更新的提醒

**Comment by 0ceanCat** [comment]
原来如此，谢谢
