### ISSUE TITLE
奇怪的问题：导入成功后出现报错 There are no bots to get.

### ISSUE THREAD

**Issue by zhulinyv** [TDK1969/nonebot_plugin_bilibilibot#31]
如图，出现如下报错。这个问题很奇怪，我在自己电脑上测试的时候是没有问题的，但是放到服务器上就会出现`There are no bots to get.`

![无标题](https://user-images.githubusercontent.com/66541860/199915047-e82022e9-ca40-4e20-9993-1cd8e0e55487.png)
![无标题1](https://user-images.githubusercontent.com/66541860/199915067-e9c67fa3-9626-4dc6-ae43-38a35b3ce611.png)
![无标题2](https://user-images.githubusercontent.com/66541860/199915096-474a40e4-a992-4220-abac-e0537ff9c8b4.png)
![无标题3](https://user-images.githubusercontent.com/66541860/199915112-4ec48bc4-d29e-432b-b8f2-9349b490aacf.png)

**Comment by TDK1969** [comment]
这我还真不知道咋回事，可能是nonebot版本不同？

**Comment by zhulinyv** [comment]
> 这我还真不知道咋回事，可能是nonebot版本不同？

都是rc1，python3.9，但是服务器上就报错QAQ...
