### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by YouYouLip** [TDK1969/nonebot_plugin_bilibilibot#35]
请问Job "check_bili_live (trigger: interval[0:01:00], next run at: 2022-12-22 07:23:16 CST)" raised an exception
这种报错是什么原因（我没有全截上忘了这个事了只截了这个）貌似是apscheduler触发的这个报错
这个报错仅限我关闭显示屏后会出现 早上挂到晚上2 3点都没事 但是一关显示屏熄屏下运行就会出现这种错误 bot会显示raise ValueError("There are no bots to get.") gocq会显示已离线重连失败这种错误 是插件自身原因还是其他的呢

**Comment by TDK1969** [comment]
这个我也不清楚，应该不是插件的问题，建议查看gocq的log

**Comment by YouYouLip** [comment]
> 这个我也不清楚，应该不是插件的问题，建议查看gocq的log

这个报错我想我应该知道了...我测试了几天 nonebot商店里有个fortune这个今日运势插件 他依赖的apscheduler是1.4版本 就是我安装这个插件会强制给我安装1.4 然后我部分插件是2.0依赖 然后我通过升级apscheduler指令强制升回2.0然后这个插件虽然可以运行 但是貌似每日刷新抽签记录会出错 我卸载后3 4天了都没事

**Comment by ElainaFanBoy** [comment]
> > 这个我也不清楚，应该不是插件的问题，建议查看gocq的log
> 
> 这个报错我想我应该知道了...我测试了几天 nonebot商店里有个fortune这个今日运势插件 他依赖的apscheduler是1.4版本 就是我安装这个插件会强制给我安装1.4 然后我部分插件是2.0依赖 然后我通过升级apscheduler指令强制升回2.0然后这个插件虽然可以运行 但是貌似每日刷新抽签记录会出错 我卸载后3 4天了都没事

您好，我也遇到了这个报错，请问有没有合适的解决方法
