### ISSUE TITLE
指令报错

### ISSUE THREAD

**Issue by TTH23** [TDK1969/nonebot_plugin_bilibilibot#4]
![image](https://user-images.githubusercontent.com/78184207/163290452-7654b0e4-e028-477b-9c28-0d42e738c13a.png)
![image](https://user-images.githubusercontent.com/78184207/163290463-fcc8170f-e54b-462a-997b-dda8aea2fb29.png)
![image](https://user-images.githubusercontent.com/78184207/163290474-894b7d54-cefe-427f-96b1-2cc057b4cc9c.png)
下载zip后把file拖进C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\nonebot_plugin_bilibilibot后报错如下
![image](https://user-images.githubusercontent.com/78184207/163290614-7e02c904-b1d5-46aa-85b6-0096c9f8230b.png)
萌新 哪里有很傻的地方请指出（捂脸
beta2版本

**Comment by TDK1969** [comment]
请问是通过什么方法安装的？
下载zip后的把file拖进……后，请提供完整的日志，看不到具体的报错

**Comment by TTH23** [comment]
使用的nb plugin install nonebot-plugin-bilibilibot指令安装的
![image](https://user-images.githubusercontent.com/78184207/163306643-6b38ed23-380f-47c0-8789-7b5ffc999daf.png)
![image](https://user-images.githubusercontent.com/78184207/163306666-fd255b47-6f00-4a99-965b-a0dc8c1a1aaf.png)
这是导入的图片 txt点进去看了是有文字的
![image](https://user-images.githubusercontent.com/78184207/163306716-4cf246c3-aed9-4b2c-b300-dd13ebfbda9a.png)
C:\Users\28339\AppData\Local\Programs\Python\Python39\Lib\site-packages\nonebot_plugin_bilibilibot\file
这是我放的路径 按照报错里的路径放置的
![image](https://user-images.githubusercontent.com/78184207/163306869-20017ae3-b9b2-40b7-a632-b4d92fe08f65.png)
这是载入的插件
![image](https://user-images.githubusercontent.com/78184207/163306951-bc80954c-068c-445b-beeb-1904c0a374a6.png)
这是site-packages文件夹

**Comment by TDK1969** [comment]
可能是编码的问题？我研究一下

**Comment by TDK1969** [comment]
你可以试一下修改__init__.py文件中的sendHelpMsg函数，修改为如下内容：
```python
async def sendHelpMsg(event: MessageEvent):
    userID = event.sender.user_id
    helpMsg = ""
    with open(f'{PackagePath}/file/source/help.txt', 'r', encoding='utf-8') as f:
        helpMsg = f.read()
    await helpCommand.finish(helpMsg)
```
看看这样还会不会报错

**Comment by TDK1969** [comment]
请更新到2.0.3版本，修复了该问题
如果问题仍然存在，请向我反馈
