### ISSUE TITLE
关注up主 ['(未知错误,请查看日志)']

### ISSUE THREAD

**Issue by CheatManager** [TDK1969/nonebot_plugin_bilibilibot#42]
05-08 13:22:50 [ERROR] nonebot_plugin_bilibilibot | [bilibilibot~视 频 ]【 错 误 报 告
】
关 注 up主  <1340190821>时 发 生 意 料 之 外 的 错 误
错 误 类 型 : <class 'json.decoder.JSONDecodeError'>
错 误 值 : Extra data: line 1 column 47 (char 46)
Traceback (most recent call last):
  File "/root/qqbot/.venv/lib/python3.10/site-packages/nonebot_plugin_bilibilibo
t/bili_src/biliVideo.py", line 81, in follow_up
                                up_name, latest_timestamp = await bili_client.in
  _up_info(uid)
  File "/root/qqbot/.venv/lib/python3.10/site-packages/nonebot_plugin_bilibilibo
t/bili_src/bili_client.py", line 186, in init_up_info
                                response2 = response2.json()
  File "/root/qqbot/.venv/lib/python3.10/site-packages/httpx/_models.py", line 7
56, in json
  turn jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 47 (char 46)

**Comment by ElainaFanBoy** [comment]
> 05-08 13:22:50 [ERROR] nonebot_plugin_bilibilibot | [bilibilibot~视 频 ]【 错 误 报 告
> 】
> 关 注 up主  <1340190821>时 发 生 意 料 之 外 的 错 误
> 错 误 类 型 : <class 'json.decoder.JSONDecodeError'>
> 错 误 值 : Extra data: line 1 column 47 (char 46)
> Traceback (most recent call last):
>   File "/root/qqbot/.venv/lib/python3.10/site-packages/nonebot_plugin_bilibilibo
> t/bili_src/biliVideo.py", line 81, in follow_up
>                                 up_name, latest_timestamp = await bili_client.in
>   _up_info(uid)
>   File "/root/qqbot/.venv/lib/python3.10/site-packages/nonebot_plugin_bilibilibo
> t/bili_src/bili_client.py", line 186, in init_up_info
>                                 response2 = response2.json()
>   File "/root/qqbot/.venv/lib/python3.10/site-packages/httpx/_models.py", line 7
> 56, in json
>   turn jsonlib.loads(self.text, **kwargs)
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 1 column 47 (char 46)

同问题

**Comment by DanLCJ** [comment]
同问题

**Comment by TDK1969** [comment]
收到

**Comment by DanLCJ** [comment]
目前排查下来可能是json的结构改变了，导致load的时候报错。目前通过人为修改数据库可以实现动态更新，dynamic中有数据的情况下，私聊和群聊都可正常添加有数据的up关注；反之则不可。

**Comment by TDK1969** [comment]
@DanLCJ 是的，我也感觉是。如果可以的话能够帮我做一个测试：
在`bili_src/bili_client.py`中修改函数`init_up_info`，在第171行前添加如下代码：
```
logger.debug(response1.text())
```
然后再使用关注命令，在log中查看debug的结果。

**Comment by TDK1969** [comment]
已经确认使用的接口返回有改变，会在解下来几天内修复

**Comment by TDK1969** [comment]
已在2.3.2版本更新中解决

**Comment by phquathi** [comment]
nb plugin install还没更新吗 急急急

**Comment by ElainaFanBoy** [comment]
> nb plugin install还没更新吗 急急急

源没同步上的话你可以去pypi下whl安装

**Comment by TDK1969** [comment]
> nb plugin install还没更新吗 急急急

我在pypi那里传了呀
<img width="809" alt="image" src="https://github.com/TDK1969/nonebot_plugin_bilibilibot/assets/54183084/c4db212b-8958-4451-8d66-47cb26ea51fa">

**Comment by phquathi** [comment]
![V(EGHEZZ0@EHP @4_N$%V}P](https://github.com/TDK1969/nonebot_plugin_bilibilibot/assets/131594704/4e7974b6-00ac-4dac-a467-4581c2c277a9)

**Comment by ElainaFanBoy** [comment]
> ![V(EGHEZZ0@EHP @4_N$%V}P](https://github.com/TDK1969/nonebot_plugin_bilibilibot/assets/131594704/4e7974b6-00ac-4dac-a467-4581c2c277a9)
> 

你用的源还没更新，你可以直接去pypi直接下包，下到本地再安装就行

**Comment by phquathi** [comment]
嗷嗷懂了 那我等他更新吧 谢谢你们❤

**Comment by DanLCJ** [comment]
> @DanLCJ 是的，我也感觉是。如果可以的话能够帮我做一个测试： 在`bili_src/bili_client.py`中修改函数`init_up_info`，在第171行前添加如下代码：
> 
> ```
> logger.debug(response1.text())
> ```
> 
> 然后再使用关注命令，在log中查看debug的结果。

不好意思这几天没留意这里，辛苦啦
