### ISSUE TITLE
获取up主时接口返回错误,接口错误码为:-403

### ISSUE THREAD

**Issue by ElainaFanBoy** [TDK1969/nonebot_plugin_bilibilibot#44]
05-19 21:42:23 [ERROR] nonebot_plugin_bilibilibot | [[bilibilibot~视频]][错误报告]
检测up主 <109313689> 更新情况时发生错误
错误类型: <class 'src.plugins.nonebot_plugin_bilibilibot.bili_src.exception.BiliAPIRetCodeError'>
错误信息: 获取 up主 <109313689> 时接口返回错误
接口错误码为:-403
接口错误信息为:访问权限不足

**Comment by TDK1969** [comment]
我还没遇到过这种情况诶，能提供更多信息吗，比如能否稳定复现等？

**Comment by TDK1969** [comment]
在b站涉及空间的api换接口后，对鉴权有了新的要求，见https://github.com/SocialSisterYi/bilibili-API-collect/issues/631#issue-1608317557
因此会经常性地出现-403的错误

**Comment by ElainaFanBoy** [comment]
> 在b站涉及空间的api换接口后，对鉴权有了新的要求，见https://github.com/SocialSisterYi/bilibili-API-collect/issues/631#issue-1608317557
> 因此会经常性地出现-403的错误

大佬，我看这个issue里好像已经解决了，要不更新下（）

**Comment by TDK1969** [comment]
过几天更新

**Comment by ElainaFanBoy** [comment]
> 过几天更新

好的，辛苦了

**Comment by WTTSFW** [comment]
请问更新了吗

**Comment by qwqZYLqwq** [comment]
“过几天更新”

**Comment by TDK1969** [comment]
请更新到2.3.3，已修复该问题
