### ISSUE TITLE
获取动态使用的接口返回-352错误

### ISSUE THREAD

**Issue by TDK1969** [TDK1969/nonebot_plugin_bilibilibot#47]
目前暂时无法获取动态，正在研究解决办法

**Comment by Von0115** [comment]
目前是不是只能推送直播？

**Comment by TDK1969** [comment]
@Von0115 动态的问题已解决，视频的问题最近忙没搞。
我等会开个issue说明一下怎么修复获取动态。

**Comment by Von0115** [comment]
> @Von0115 动态的问题已解决，视频的问题最近忙没搞。
> 我等会开个issue说明一下怎么修复获取动态。

感谢大佬，辛苦了

**Comment by TDK1969** [comment]
修复方法见https://github.com/TDK1969/nonebot_plugin_bilibilibot/issues/49

**Comment by TDK1969** [comment]
请更新到版本2.3.3，已修复该问题
