### ISSUE TITLE
。。。网络正常的情况下报错。。。

### ISSUE THREAD

**Issue by WTTSFW** [TDK1969/nonebot_plugin_bilibilibot#55]
![image](https://github.com/TDK1969/nonebot_plugin_bilibilibot/assets/85236395/226dc1ce-9b06-4726-8126-f82ab5b56c9b)

**Comment by TDK1969** [comment]
<img width="544" alt="image" src="https://github.com/TDK1969/nonebot_plugin_bilibilibot/assets/54183084/e78ab007-42f6-496c-bebd-79d266676a34">

我这里没有出现这个问题，你这边网络错误的问题能稳定复现吗
