### ISSUE TITLE
[Bug]: 订阅的番剧不推送了

### ISSUE THREAD

**Issue by cj1357** [TDK1969/nonebot_plugin_bilibilibot#57]
### billibilibot 版本

2.2.3

### nonebot 版本

2.0

### go-cqhttp 版本

2.0.0

### 运行环境

Linux

### 重现步骤

订阅了番剧“葬送的芙莉莲”，每周二20:00更新，几周前每周二还能推送更新，这两周没有推送了

### 期望的结果是什么？

可以继续推送

### 实际的结果是什么？

番剧没推送

**Comment by TDK1969** [comment]
1. 在对应日期的info.log里面查找，是否存在番剧更新信息，格式为`[bilibilibot~番剧] 检测到影视剧 <> 更新`。
2. 如果存在此类信息，检查同一天的error.log，查看是否为信息发送过程中发生错误。
3. 如果不存在，继续与我联系

**Comment by cj1357** [comment]
找了26号周二这一天所有的info、error的log，没有bilibilibot番剧相关的更新信息及报错

我订阅的是这个ss46089

**Comment by cj1357** [comment]
我搜索了一下，是12月12号推送之后就不再推送了，途中周一误推送了一次，而且集数不对，12月12号推送的也不对，现在最新才13集。

是不是bilibot推送的记录已经到14集了，就不再继续推送了

今天20点也会更新第14集，看这次推不推送了

![image](https://github.com/TDK1969/nonebot_plugin_bilibilibot/assets/40661342/527cd8e0-a417-4417-b0ef-95c5de6de6ab)

**Comment by TDK1969** [comment]
好的，感谢你提供的信息。
还想问一下，插件在推送《葬送的芙莉莲》时出现了集数不对的情况，请问是什么时候开始出现这个现象的？

**Comment by cj1357** [comment]
> 好的，感谢你提供的信息。 还想问一下，插件在推送《葬送的芙莉莲》时出现了集数不对的情况，请问是什么时候开始出现这个现象的？

是上面截图12月11号（周一）的时候，番剧是周二更新的，周一却推送了一次13集的，之前那周二推送的还是第10集

**Comment by cj1357** [comment]
葬送的芙莉莲突然改成每周五更新了，难道是规则改了导致的吗，我这周五再看看有没有更新

**Comment by TDK1969** [comment]
> 葬送的芙莉莲突然改成每周五更新了，难道是规则改了导致的吗，我这周五再看看有没有更新

好的，我估计不推送是因为某种错误导致数据库中记录的集数错误，因为在代码中是通过比较集数来判断是否有更新的，或许可以考虑通过时间比较

**Comment by cj1357** [comment]
原来如此😺

**Comment by cj1357** [comment]
明明是周五更新的，今天周三却推送了第16集，bilibili番剧那边最新也才13集，难道是预告导致的？
![image](https://github.com/TDK1969/nonebot_plugin_bilibilibot/assets/40661342/53de882a-ed69-4320-9421-1cb8ae19aca5)

**Comment by TDK1969** [comment]
我这边已经复现了这个问题，我看一下

**Comment by TDK1969** [comment]
我排查出原因了，确实是因为预告，我调用的接口把预告插在了正片的列表里面，导致不能直接用下标获取对应的集数。

**Comment by cj1357** [comment]
这种有预告的番剧就比较难办了

**Comment by TDK1969** [comment]
我修改好了，等我测试几天就更新

**Comment by TDK1969** [comment]
![image](https://github.com/TDK1969/nonebot_plugin_bilibilibot/assets/54183084/594ed37b-e694-4551-8dd7-2636f9952731)

**Comment by TDK1969** [comment]
预告更新能正常通知
![image](https://github.com/TDK1969/nonebot_plugin_bilibilibot/assets/54183084/46212a91-0964-487c-8768-6d178a519c0a)

**Comment by cj1357** [comment]
哇，预告都有了，好耶😀

**Comment by TDK1969** [comment]
请更新到版本2.3.4，已解决该问题

**Comment by cj1357** [comment]
感谢大佬，辛苦了😺
