### ISSUE TITLE
指令在部分群失效

### ISSUE THREAD

**Issue by huichenmoyan** [TDK1969/nonebot_plugin_bilibilibot#6]
机器人在部分群中可正常返回信息:
![W@9JCR`L~H~~%~{P0KMYJEL](https://user-images.githubusercontent.com/65167412/166135593-acff167e-17aa-421f-94f4-eef7b611252b.png)

但在部分群中不返回任何信息:
![5SW}D92~TD6~3IVQ({V{ZN1](https://user-images.githubusercontent.com/65167412/166135630-f50e405a-1fae-48ec-b969-e643a2d85c07.png)

且收到了后台报错：
![TV2F2$5XI0@2M1SUM@2)1C6](https://user-images.githubusercontent.com/65167412/166135714-069705d1-bedf-44e5-972d-d718cd6a36a3.png)

![T``EKUF)%BLT1OHOT1J7)T8](https://user-images.githubusercontent.com/65167412/166135675-13e58a60-870b-4ae9-a767-23674d8c9c05.png)

在所有群中发消息的账号都有管理员权限，已确认nonebot与该插件的配置无误。
nonebot版本:2.0.0-beta2
插件版本:2.0.3

**Comment by TDK1969** [comment]
1. 请问nonebot运行的系统是什么？
2. 请在目录`C:\Users\huich\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\file\group`中检查两个群的json文件（文件名为`群号.json`），并将发送失败的群的json文件内容发出来看看。

**Comment by huichenmoyan** [comment]
1.Windows 11 22598.200
2.
![MEW)`~ R @_E H(0NWW%QIO](https://user-images.githubusercontent.com/65167412/166178710-b48e26d3-3425-417b-9b9d-7c768da40226.png)
如图，完全没有内容

**Comment by TDK1969** [comment]
请尝试删除该文件，并且重新在该群发送命令
在日志中查看是否有`用户文件不存在，准备创建`，并且再次查看该群的json文件

**Comment by huichenmoyan** [comment]
已尝试删除，有该消息，但仍报错。
![7EUAAJKDKL)@EDO6~T3W2)R](https://user-images.githubusercontent.com/65167412/166184409-7b6fdbb5-b8c3-480c-aaa9-812094a50cd0.png)
![D7@@G{X85LE@SKA7LUR3KW9](https://user-images.githubusercontent.com/65167412/166184411-3c26cef5-b909-4aaf-89cf-c6e159a8bd9f.png)

**Comment by TDK1969** [comment]
我已复现问题，并定位到错误位置，请先删除发生错误的群的文件（如果存在），并进行以下操作。
请尝试修改`C:\Users\huich\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\__init__.py`中的函数`listFollowingCommandHandler`，将`groupInfo = await bot.get_group_info(group_id=id)`修改为`groupInfo = await bot.get_group_info(group_id=groupID)`，并查看运行情况。

**Comment by huichenmoyan** [comment]
![M ~U{()RF4Q@IO7 %UKQJLP](https://user-images.githubusercontent.com/65167412/166213621-c1bccd1d-1ace-4b95-9f9f-1184330d3528.png)
如图，已修改完毕，后台扔报错：
![) DHH5LJFBINYCI1@VB5 B](https://user-images.githubusercontent.com/65167412/166213662-09e4085a-fe39-48fa-a15f-c5c9c3519720.png)
![XPWT58`$~PJR4{AMCH V74](https://user-images.githubusercontent.com/65167412/166213692-32b004f2-8a76-4106-b7bf-bf1a823e8f8c.png)
估计是编码的问题？

**Comment by TDK1969** [comment]
能问一下群名是什么嘛 感觉是群名里面的一些字符导致了这个问题？

**Comment by huichenmoyan** [comment]
![$LS}K9_0XA5M ~NP 4C0XQM](https://user-images.githubusercontent.com/65167412/166218633-18fc4c7e-18d3-4141-9ce3-f3738fa8165e.png)
可能是这个前缀和后缀的问题？

**Comment by TDK1969** [comment]
有可能，请问可以将这个群名用文字形式发出来吗，我再进行进一步的测试，谢谢

**Comment by huichenmoyan** [comment]
<$ǿĀD>

**Comment by TDK1969** [comment]
我大概明白是什么的问题了，我在创建文件时没有指定编码方式，导致一些特殊字符会导致编码的问题。你的问题中显示使用gbk编码时会出现编码错误，如果编码方式指定为utf-8，就应该不会产生这样的错误。
![image](https://user-images.githubusercontent.com/54183084/166422291-6378e36f-977d-4139-8cc1-00bd45999b92.png)

**Comment by TDK1969** [comment]
请尝试修改`C:\Users\huich\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\basicFunc.py`中的函数`createUserFile`，将`with open(userFile, 'w+') as f:`修改为`with open(userFile, 'w+', encoding='utf-8') as f:`，再进行测试，问题应该能够得到解决。

**Comment by huichenmoyan** [comment]
好的，问题解决了，感谢！

**Comment by TDK1969** [comment]
感谢你的反馈，请更新至版本2.0.4

**Comment by huichenmoyan** [comment]
顺带问一下，这个bot的查询间隔大概是多少呢？现在好像因为查询过快，容易被b站封ip。
![02$ZGL1Q4MT4JETYDL%(@78](https://user-images.githubusercontent.com/65167412/166448895-656cd07c-2314-49a1-9745-6d37cde63c71.png)
如图，我看这个议题也出现了相同的问题。日志我和他的差不多，我就不重复发了。
![9@(M) ))I3OE@GG)K YPNC7](https://user-images.githubusercontent.com/65167412/166449110-b29e890c-28b4-4e80-9718-30301e8d4b07.png)
我看bilibili-api这个pip库是这么解释的，希望有帮助。

**Comment by TDK1969** [comment]
不知道我和bilibili-api用的是否是同一个api，我是直接在网页上爬的，我暂时没有遇到这样的问题
直播的查询频率是10s，视频是1分钟，番剧是5分钟
如果想更改查询的频率，可以修改__init__.py文件中最后部分使用scheduler的代码，如果担心请求速度过快，可以将直播查询的频率修改为`minutes=1`

**Comment by huichenmoyan** [comment]
好的，我修改了看看，明天给出答复。

**Comment by huichenmoyan** [comment]
问题已解决，频率均为5分钟一次。

**Comment by TDK1969** [comment]
> 问题已解决，频率均为5分钟一次。

好的
