### ISSUE TITLE
建议超级管理员也算上ALL_PERMISSION

### ISSUE THREAD

**Issue by jcjrobert** [TDK1969/nonebot_plugin_bilibilibot#7]
from nonebot.permission import SUPERUSER

ALL_PERMISSION = GROUP_ADMIN | GROUP_OWNER | PRIVATE_FRIEND | SUPERUSER

**Comment by jcjrobert** [comment]
顺便建议查询关注把up主播番剧合在一起发送
三条不间隔连着一起发很容易被风控

**Comment by TDK1969** [comment]
这一点主要是考虑到机器人在群中使用的情境，如果超级管理员不是群的管理或者群主，或许不太合适？机器人由群主或者管理来操作可能更合适？

**Comment by TDK1969** [comment]
> 顺便建议查询关注把up主播番剧合在一起发送 三条不间隔连着一起发很容易被风控

这一点我倒是不知道，如果是这样的话那就需要进行修改

**Comment by jcjrobert** [comment]
> 这一点主要是考虑到机器人在群中使用的情境，如果超级管理员不是群的管理或者群主，或许不太合适？机器人由群主或者管理来操作可能更合适？

可以的，有的管理不会用就直接叫超级管理员帮忙添加，而且超级管理员本来就应该都能响应的，没问题的

**Comment by TDK1969** [comment]
有道理，感谢你的建议

**Comment by TDK1969** [comment]
感谢你的建议，请更新至版本2.0.4
