### ISSUE TITLE
使用关注主播报错

### ISSUE THREAD

**Issue by Arturia169** [TDK1969/nonebot_plugin_bilibilibot#9]
![image](https://user-images.githubusercontent.com/69199123/169473091-efa435ae-845e-494d-a37e-46b1229915cd.png)

**Comment by Arturia169** [comment]
![image](https://user-images.githubusercontent.com/69199123/169473242-45248745-295d-4242-88e8-0820ad3a1b3a.png)

**Comment by TDK1969** [comment]
感谢你的反馈，请补充如下信息：
1. 你使用nonebot的环境、bilibilibot的版本等
2. 出现问题的完整日志内容，麻烦已文字形式放在代码块中方便查看
